apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-07-27T21:14:15Z"
  name: elasticsearch
  namespace: elastic-stack
  resourceVersion: "1018"
  uid: 0e3ec742-9da9-4eea-9027-9cf8c4ee2773
spec:
  clusterIP: 10.110.247.8
  clusterIPs:
  - 10.110.247.8
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port1
    nodePort: 30200
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: port2
    nodePort: 30300
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    name: elastic-search
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}